---
- name: Mount NFS to home Directorys
  mount:
    path: "/home/{{ item.user }}"
    src:  "{{ item.get ('nfs_lif') }}:/{{ item.get ('volume') }}"
    fstype: nfs
    state: mounted
  with_items: "{{ Mount_NFS }}"

- shell: df -H | grep vol1
  register: result

- debug: var=result

