---
  - name: Add Groups
    group: 
       name: "{{ item.group }}"
    with_items: "{{ Mount_NFS }}"

  - name: Add Users + Assign to Group
    user:
       name: "{{ item.user }}"
       groups: wheel 
    with_items: "{{ Mount_NFS }}"
       
  - name: Allow wheel group to have passwordless sudo
    lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^%wheel'
        line: '%wheel ALL=(ALL) NOPASSWD: ALL'